### ISSUE TITLE
[API] POST /request/0

### ISSUE THREAD

**Issue by wesley100002001** [wesley100002001/hsin-travel#14]
新增 request，細節待商榷

**Comment by ychi** [comment]
http://localhost:5000/docs?server=http://0.0.0.0:5000&path=/api/request#PUT

新增用 PUT, partial update 再用 POST

todo: accommodations 可以是空的或有裝東西的陣列

**Comment by wesley100002001** [comment]
咦～為什麼是這樣？我以為是反過來，新增用 POST，partial update 才用 PUT？

**Comment by ychi** [comment]
http://localhost:5000/docs?server=http://0.0.0.0:5000&path=/api/request#POST

accommodations 可以是空的或有裝東西的陣列
