### ISSUE TITLE
和行程相關的日期不該需要擔心時區

### ISSUE THREAD

**Issue by ychi** [wesley100002001/hsin-travel#16]
如果 client side 傳來的日期(比如入住日)是 javascript 的 Date, 其實裡面是有時區資訊的，萬一 server 的時區和 browser 時區不同可能會因為時差所以搞錯日期。

和行程相關的日期(比如入住日、用餐日)不該需要擔心時區，client side 應該只要傳字串('2017-05-01')或是一個物件(ex: {year: 2017, month: 5, day: 1}). 

PostgreSQL 裡面其實有 date only 的資料型態，但是 js 端還沒有很好的對應，Sequelize 在下一個主要版本應該會處理這個問題:
https://github.com/sequelize/sequelize/issues/4858
https://github.com/brianc/node-pg-types/issues/50
https://github.com/brianc/node-pg-types/pull/53

在那之前我們可以先討論個格式，在傳輸的時候不要傳 timestamp, 而是只傳年月日資訊

**Comment by wesley100002001** [comment]
先簡單 echo，我同意純字串 yyyy-mm-dd

**Comment by ychi** [comment]
good, it's also ISO format
