### ISSUE TITLE
Browser refresh will get 404

### ISSUE THREAD

**Issue by wesley100002001** [wesley100002001/hsin-travel#2]
因為 ui-router 直接去改了網址，但實際上 server side 並沒有那個 resource。
解法：https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-your-server-to-work-with-html5mode
等 Client & Server side 要整合時一併解。

**Comment by ychi** [comment]
This issue was moved to ychi/travel-agency#14
