### ISSUE TITLE
[API] GET /hotels

### ISSUE THREAD

**Issue by wesley100002001** [wesley100002001/hsin-travel#23]
目前是 404

**Comment by ychi** [comment]
因為本來假定需要cursor XD
/api/hotels/{cursor}/{limit?}

可以弄個拿全部的 /api/hotels

**Comment by ychi** [comment]
http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#pagination

目前想法是先讓 GET /hotels 回傳全部, 量大到有 performance 考量再加 pagination
