### ISSUE TITLE
[API: POST] /request/:requestId/accommodation/0

### ISSUE THREAD

**Issue by wesley100002001** [wesley100002001/hsin-travel#24]
對一個存在的 request 新增 accommodation 好像該長這樣。
參考：http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#requirements

**Comment by ychi** [comment]
照他這樣講應該POST /requests/:requestId/accommodation XD?

**Comment by ychi** [comment]
先做了/requests/:requestId/accommodation
