### ISSUE TITLE
管理方應該可以看到自己負責的 Request & 非自己負責的 Request

### ISSUE THREAD

**Issue by wesley100002001** [wesley100002001/hsin-travel#4]
管理方人員可以看到自己守備區的requests和全部的requests，而且應該要pagination。目前考慮用不同的 API 拿。

**Comment by ychi** [comment]
http://localhost:5000/docs?server=http://0.0.0.0:5000&path=/api/requests/{cursor}/{limit?}#GET

用 query string 來處理守備區問題:
如果 http request 帶著 `?region=iceland` 那 server 回傳的 request 都會是 region tag 為 iceland 的。
如果帶 `?region=iceland&excludeRegion=true` 那回傳的都是 region tag 非 iceland 的。

也就是幫消費方拿資料的時候都不要帶 http query; 幫管理方拿資料的時候先發 `?region=norway` 再發 `?region=norway&excludeRegion=true`

另一個想法是 query 的格式用 includeRegion 和 excludeRegion, 兩個都可給可不給。當然這樣
`?includeRegion=paris&excludeRegion=paris` 
必定拿不到東西

**Comment by ychi** [comment]
This issue was moved to ychi/travel-agency#15
